### ISSUE TITLE
How to edit the configuration file

### ISSUE THREAD

**Issue by Attia81** [pacificclimate/ClimDown#10]
How to use the .onLoad function to edit the configuration file?!

**Comment by jameshiebert** [comment]
See the "options" section of `ClimDown`'s [user manual](https://cran.r-project.org/web/packages/ClimDown/ClimDown.pdf). `.onLoad` isn't the right thing to use. Use R's [`options`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/options.html) function and/or a [`.Rprofile`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Startup.html) file.

**Comment by Attia81** [comment]
Thanks for your help and for this good package, good work. The bccaq.netcdf.wrapper function is working fine with me and the output data seem to be ok.., but with tiny.obs example and with my data, I get '50 warnings' warning message reads as 

1: executing %dopar% sequentially: no parallel backend registered
2: In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values
3: In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values

what does this warning mean and is it influencing the output data?
Also; what is the recommended overlap period between obs and GCM?

Many thanks

**Comment by jameshiebert** [comment]
Unfortunately, both of these questions are outside of the scope of the `ClimDown` software. For `%dopar%` please refer to its [package documentation](https://cran.r-project.org/web/packages/foreach/index.html). For the overlap period, you'll have to refer to the climate downscaling scientific literature. References are provided in the `ClimDown` manual.
