### ISSUE TITLE
"Opening the input files and reading metadata"

### ISSUE THREAD

**Issue by pradhancda** [pacificclimate/ClimDown#11]
Sir,

Please help to short out this error while executing the example files of ClimDown 1.0.4

> qdm.netcdf.wrapper(tiny_obs.nc, tiny_gcm.nc, out.nc, varname = "tasmax")
[1] "Opening the input files and reading metadata"
Error in nc_open(gcm.file) : object 'tiny_gcm.nc' not found

regards,
Subhasis

**Comment by jameshiebert** [comment]
You need quotes around `tiny_obs.nc` and you should use the full path (either relative or absolute) to the input file.

E.g.

```R
qdm.netcdf.wrapper("./tiny_obs.nc", "/absolute/path/to/tiny_gcm.nc", "out.nc", varname = "tasmax")
```
