### ISSUE TITLE
Constructed Analogues Speed Up

### ISSUE THREAD

**Issue by ssobie** [pacificclimate/ClimDown#2]
The "var.bcca" call in QDM.R is very slow for large data sets (e.g. Canada-wide).

When running this function over 150 years of data, the CD_ncvar_get function in io.R is called 1,653,450 times (55115 days times 30 analogues). Removing the check for non-zero precipitation and the udunits conversion results in a speed up of ~40% in generating the "var.bcca" analogues.

This function is also used in BCCI.R to load GCM data.

**Comment by jameshiebert** [comment]
Fixed by commit 411007e2f1495ae0e182dea40d24832dd7461431
