### ISSUE TITLE
Do we need historical relationship between observation and GCMs

### ISSUE THREAD

**Issue by solomonsg** [pacificclimate/ClimDown#20]
Dear all,

I have observational data sets (1981-2010) and a number of GCMs (2015-2100) under different SSPs. So my question is 
Do I need the histircal data of the GCMs? or should i merge the historical period of GCMs to the future scenarious (e.g., 1980-2100)?
Please let me know the best way to do this.
`bccaq.netcdf.wrapper(GCM_2015-2100.nc, Obs_1981-2010.nc, out.nc, varname = "pr")

I am familiar with the Delta and SDSM, which considers historical relationships, but not with ClimDown.

& how many days doest it take to run globally for the period (1980-2100)? 

Best regards,

Solomon

**Comment by jameshiebert** [comment]
@ssobie do you know how to answer this?

**Comment by ssobie** [comment]
Hello Solomon,

You will need the historical GCM data to calibrate the downscaling method. The GCM input file should include the historical and future scenario together e.g.
bccaq.netcdf.wrapper(GCM_1980-2100.nc, Obs_1981-2010.nc, out.nc, varname = "pr")
Before running this you will also need to set the calibration period to match the observation period (or a subset of that if you prefer).
options(calibration.start=as.POSIXct('1981-01-01', tz='GMT'))
options(calibration.end=as.POSIXct('2010-12-31', tz='GMT'))

The time required to run the method will depend on the resolution of your observational target dataset. For a global dataset if the resolution is high it could take a few days for each GCM simulation.

**Comment by solomonsg** [comment]
Thank you very much @ssobie and @jameshiebert
