### ISSUE TITLE
Running ClimDown on HPC 

### ISSUE THREAD

**Issue by solomonsg** [pacificclimate/ClimDown#21]
Dear @jameshiebert @ssobie

I am using climdow to downscale about 20gcms for global studies (extreme focused). I am running it on HPC with large number of cores (one node up to 65 cores) and I want make sure i am using this efficiently. I followed the instruction: 
registerDoParallel(cores=40) and compared it to with 10 cores, but don’t see the difference ( still running 

`"Computing the temporal mean"`
`"Reading timesteps 651 : 676 / 10957 from file: global_1981_2010.nc".` status on day 2.

So, there anything I can add to improve this to finish in a reasonable time. 

Best regards,

Solomon

**Comment by jameshiebert** [comment]
Hi Solomon,

We don't have the resources to provide full support for distributed HPC computing (see if your HPC provider offers it), but we can provide some rough guidance from our experience. You said that you followed the instructions, but per chance did you read the section [about performance in the README](https://github.com/pacificclimate/ClimDown#necessary-resources-performance-and-platform). The process can definitely take a long time to run.

Sounds like the CI stage is going slow for you. The CI phase is I/O bound and using more cores will not speed it up. We run this stage with one core. If you set the [`max.GB` option](https://github.com/pacificclimate/ClimDown/blob/master/R/ClimDown.R#L34) higher, you should be able to read in more data at a time in larger chunks which will help. But make sure that your data files are as local as possible to speed up the I/O (we use node local scratch storage on SSDs). Data locality is the key to running ClimDown effectively.

Do review the [User-configurable options](https://github.com/pacificclimate/ClimDown/blob/master/R/ClimDown.R#L27) as there are a number of ways to tweak and customize your usage of ClimDown.

Hope that helps.

**Comment by solomonsg** [comment]
thanks @jameshiebert. I was trying with different max.gb and indeed its much faster when max.GB is higher
` "Interpolating timesteps 1 - 26 / 43464 to file /tmpR/file2401f2f0d1a91.nc"` with defult max.GB 
`"Interpolating timesteps 1 - 13037 / 43464 to file /tmpR/file277be16409cf9.nc" with max.GB=500.
