### ISSUE TITLE
Error in Rsx_nc4_get_vara_double: NetCDF: Index exceeds dimension bound

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/ClimDown#6]
From David Gampe <d.gampe@iggf.geo.uni-muenchen.de>

> Hi!
> 
> I want to bias correct climate model data using R and found the R-package
> "ClimDown". However, I fail to execute the wrappers, and always get the
> following error:
> 
> 

```R
/[1] "Opening the input files and reading metadata"//
//[1] "Calculating the time factors outside in order to subdivide the problem space"//
//Creating output file out.nc //
//[1] "Bias correcting pr longitudes 0 - 1 / 0"//
//[1] "Reading longitudes 0 - 1 / 0 from file: pr_EUR-05_SMHI-HIRLAM_reanalysis_v1d1-v1d2_SMHI-MESAN_v1_day_19890101-20101231_cut_RemapEUR-11.nc"//
//[1] "... and reading latitudes 1 - 0 / 0"//
//Error in Rsx_nc4_get_vara_double: NetCDF: Index exceeds dimension bound//
//Var: pr  Ndims: 3   Start: 0,0,4294967295 Count: 8034,9,2//
//Error in ncvar_get_inner(ncid2use, varid2use, nc$var[[li]]$missval, addOffset,  : //
//  C function R_nc4_get_vara_double returned error/
```

> i then tried to run the function qdm.netcdf.wrapper line by line to debug and
> find the error and encountered the problem, that the function
> "compute.time.stats" (at the beginning of the function) is missing. I could
> not find anything in the internet on this function. Can you maybe help me with
> this? Which package am I missing? (Or is this a problem related to my OS -
> windows 10 ?)

**Comment by jameshiebert** [comment]
I see a couple of odd things from the output. The part of the code that this is failing in is where it tries to divide the input data into chunks and process them one chunk at a time.

1. ".. and reading latitudes 1 - 0 / 0" It looks like the chunking code didn't compute a valid ending index, as it's trying to start at index 1 and read until index 0 (which is quite wrong).
1. "pr  Ndims: 3   Start: 0,0,4294967295 Count: 8034,9,2". The data read is trying to start at index 4 billion (+ some change). Do you actually have that many timesteps in this file? If not, something is going very wrong.

If you could drop an input file on Google Drive or Dropbox or something, I'd be happy to take a look at it.

**Comment by davidgampe** [comment]
Thanks for your help and bringing this here! I attached both ncdumps for the "observational" data set used (MESAN) and the climate model data (CORDEX). Please find the corresponding files here: [https://syncandshare.lrz.de/dl/fi6wg27VwKixKD6LrXwh9Yc4/ClimDownIssues.tar](url)

Thanks for your help!

Cheers,
David

[ncdumpCORDEX.txt](https://github.com/pacificclimate/ClimDown/files/1067602/ncdumpCORDEX.txt)
[ncdumpMESAN.txt](https://github.com/pacificclimate/ClimDown/files/1067603/ncdumpMESAN.txt)

**Comment by jameshiebert** [comment]
Thanks for posting your input files! I took a look at the issue, and there are a couple issues. `ClimDown` starts the whole process by interpolating the GCM grid to the observational grid. In your case, the grids are both the same:

```R
Browse[2]> all.equal(gcm.lats, obs.lats, tolerance=.001)
[1] TRUE
Browse[2]> all.equal(gcm.lons, obs.lons, tolerance=.001)
[1] TRUE
```
This package is really designed to *downscale* from a coarse grid to a fine grid, and if that's not your use case, then this might not be the right software for you. If you're simply looking to bias correct, there are probably much simpler ways to do that. This package bias corrects as part of the entire process, but it doesn't export/expose any methods that *only* bias-correct.

The other problem here is that [grid handling code](https://github.com/pacificclimate/ClimDown/blob/master/R/CI.R#L203) naively looks for regular `lat` and `lon` variables. It won't handle grids like yours where there are x and y coordinate dimensions, with latitude not being directly attached to the variable:

```bash
$ ncdump -v lon pr_EUR-11_MPI-M-MPI-ESM-LR_historical_r1i1p1_SMHI-RCA4_v1a_day_19890101-20101231_cut.nc 
netcdf pr_EUR-11_MPI-M-MPI-ESM-LR_historical_r1i1p1_SMHI-RCA4_v1a_day_19890101-20101231_cut {
dimensions:
	x = 7 ;
	y = 9 ;
	time = UNLIMITED ; // (8035 currently)
	nb2 = 2 ;
variables:
	double lon(y, x) ;
		lon:standard_name = "longitude" ;
		lon:long_name = "longitude" ;
		lon:units = "degrees_east" ;
		lon:_CoordinateAxisType = "Lon" ;
```
```R
Browse[2]> dim(gcm.lats)
[1] 7 9
Browse[2]> length(gcm.lats)
[1] 63
```
This *would* be useful functionality to have, and we can file and enhancement issue for that.

Long-story-short, I don't think that this package is quite aligned with your use case. I'll close this ticket for now, but feel free to re-open if I have misunderstood something.

**Comment by davidgampe** [comment]
Hi!

Sorry to re-open this. I only remapped the reference grid to the RCM grid, as it did not work with the original grids resolution (~5km). The second problem however is probably the one where I fail. Could you maybe upload a small example file which has the correct lat&lon information? Then I will try to re-shape my netcdfs... Thanks again! (I would love to downscale and bias correct simultanously, that would be the perfect scenario, that's why I re-opened this again :))

**Comment by jameshiebert** [comment]
Hi David,

The [package tarball](https://cran.r-project.org/src/contrib/ClimDown_1.0.2.tar.gz) ships with a couple of example files that are used in the test suite. Look for [tests/tiny_gcm.nc](https://github.com/pacificclimate/ClimDown/blob/master/tests/tiny_gcm.nc) and [tests/tiny_obs.nc](https://github.com/pacificclimate/ClimDown/blob/master/tests/tiny_obs.nc).

**Comment by jameshiebert** [comment]
Having not heard anything for a couple of months, I'm going to go ahead and close this.
