### ISSUE TITLE
l have a question that is CI a downscaling method in the package "ClimDown?. I only use Ci to scale down, that is OK?

### ISSUE THREAD

**Issue by wenwenlithanks** [pacificclimate/ClimDown#8]
hi, thank you for your great work. but l have a question that is CI a downscaling method in the package "ClimDown?. I only use Ci to dwonscale, that is OK?

**Comment by jameshiebert** [comment]
I can't really answer that question as a software developer. Whether it's OK or not would depend on the goals of your study and what you're trying to achieve. It's more of a scientific methods question, and for that you would have to consult with some climate statisticians.
